### ISSUE TITLE
React boilerplate

### ISSUE THREAD

**Issue by hitman99** [hitman99/shitty-gifs#1]
Need to setup react boilerplate for frontend

**Comment by theTechie** [comment]
you need a react app to start building your frontend? I can help @hitman99

**Comment by hitman99** [comment]
Hi, I was about to setup non react-create-app boilerplate. I don't like the bloat it brings, 'm looking for very minimal, very clean webpack setup for dev and prod. Is this something you can do ?

**Comment by theTechie** [comment]
Yes. Do you want Babel? Do you write in ES6?

**Comment by theTechie** [comment]
I have added a minimal one using just webpack and babel 👍

**Comment by hitman99** [comment]
Resolved
